### ISSUE TITLE
Foto of schema possible?

### ISSUE THREAD

**Issue by lobocobra** [danimaciasperea/Calduino#6]
A great project! Congratulation!

**My aim**
I am looking for a way to integrate my heating (BuderusGB 125 with MC10 and RC35) into openhab. I have already a SONOFF in the MC10, which enables me to read temperatures and to force the heating to fire up. The SONOFF POW also calculates how much oil is in the tank left. I understood, that your EMS interface is acting as a server with a web-interface. I would like now use NODE-RED to transform the requests to MQTT and have openhab to control the heating of my house.

**Your solution**
I found now your great project and would like to do the same. I found the schema/layout of the interface that you build, but as I am much less in electronics than you, I would ask you, if you could upload some clear photos of the actual soldered interface from both sides, which could help me (and others?) to understand the layout much better and to copy it 1:1. 
=> I will then ask an electronic shop to provide me the parts you have listed
=> and with the help of the photo I would be much more secure to replicate your interface

Many thanks!

P.S.
Do you think it is possible to have a SONOFF device with ARENDST firmware to hook up directly to the EMS bus with a 266 chip?

**Comment by danimaciasperea** [comment]
Hello,

I have updated my blog post to include a layout of the circuit in a more comprehensive way. Find it [here](https://domoticproject.com/calduino-connecting-arduino-ems-bus/#Calduino_Puting_it_al_together). Serial port should be connected in pin 14 for TX and 15 for RX. 

However, my circuit was designed to fit with an Arduino Mega. I don't know what microprocessor are you going to use to interact with the EMS Bus.

You mentioned that my EMS interface acts as a server with a web interface. However, it only acts as a bridge between received/sent commands over WiFly’s TCP/IP socket and the EMS Bus. The "logic" and web interface lives in a Raspberry Pi running WeeWX.

To say the true, I don't have practical experience with SONOFF, ARENDST, NODE-RED or openhab. I have donde some request and I don't get where can be useful to hock directly the SONOFF device to the EMS Bus with the ESP 8266 chip. If you want to connect this module to the EMS Bus, I think it will be much easier to directly buy one (it costs less than 5 €) and connect it though the circuit interface. Serial access to the EMS Bus is a little bit tricky as explained in my blog's post. However, in this [Project](https://github.com/proddy/EMS-ESP-Boiler) you can find some code regarding how to connect it.

Regards,

Daniel

**Comment by proddy** [comment]
Hi lobocobra, Daniel supported me on my ESP8266 version which he referenced above. The schematics are available there and I'm working on a revised version with board prints. The code works standalone on most ESP8266 devices (including Sonoff dev boards) and also a port to Tamota and Espurna.

**Comment by lobocobra** [comment]
Hi both

Many thanks for the responses, that sounds great, so I could integrate it into SONOFF. 
=> I wrote already a couple of SONOFF drivers, so I hope you guys are cool with it, if I try to integrate it into a sonoff driver.
=> Reason is that sonoff uses less power and I can add 5-6 Temp sensors and fire up my heating.

**Question**
Do you know if the layout mentionned above does accept 3.3V input or only 5V? The newly posted layout I can much better understand/copy (as I have only basic know-how in electronic). 
=> But I would be unable to modify it, in order to run it with 3.3V, can you confirm that this would work? Means, can a SONOFF with 3.3V on TX/RX talk through the interface with the 12V Buderus?

**Comment by proddy** [comment]
The circuit on my project works with both 3.3 and 5v.

**Comment by danimaciasperea** [comment]
You should be able to adapt the circuit to a 3.3V input with very few changes. @proddy  uses @bbqkees circuit, have a look at his [board designs](https://github.com/bbqkees/Nefit-Buderus-EMS-bus-Arduino-Domoticz/tree/master/PCB-files/V0.9). He has already done a 3.3 V compatible circuit.

**Comment by lobocobra** [comment]
Thanks @proddy  
You made my day :-) 

@danimaciasperea  
Thanks  for your feedback, but adapting a circuit is above my capabilities, I gonna stick to the design that works already with 3.3v

I will update my journey here for others and will report what happens next :-)
